---

- name: Destroy infrastructure using Terraform
  terraform:
    project_path: "{{ role_path }}/terraform"
    state: absent
    variables:
      cluster_name: "{{ cluster_name }}"
      base_domain: "{{ base_domain }}"
      vpc_cidr: "{{ vpc_cidr | default(omit) }}"
      rhcos_ami: "{{ rhcos_ami }}"
      keypair_name: "{{ keypair_name }}"
    backend_config:
      bucket: "{{ terraform_bucket }}"
      key: terraform.tfstate
  register: r_terraform_apply
