---

- name: Install required packages
  yum:
    name:
      - git
      - httpd
      - screen
      - unzip
      - vim
      - wget
    state: present
  become: yes

- name: Create temporary download directory
  tempfile:
    state: directory
  register: r_create_temp_download_dir

- name: Install OpenShift installer and client
  block:
    - name: Download and unarchive OpenShift installer
      unarchive:
        src: http://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-install-linux-{{ openshift_version }}.tar.gz
        dest: "{{ r_create_temp_download_dir.path }}"
        remote_src: yes

    - name: Copy OpenShift installer binary
      copy:
        src: "{{ r_create_temp_download_dir.path }}/openshift-install"
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: 0755
      become: yes

    - name: Download and unarchive OpenShift client
      unarchive:
        src: http://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-client-linux-{{ openshift_version }}.tar.gz
        dest: "{{ r_create_temp_download_dir.path }}"
        remote_src: yes

    - name: Copy OpenShift client binaries
      copy:
        src: "{{ r_create_temp_download_dir.path }}/{{ item }}"
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: 0755
      become: yes
      loop:
        - oc
        - kubectl
  always:
    - name: Cleanup temporary download directory
      file:
        path: "{{ r_create_temp_download_dir.path }}"
        state: absent

- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes
