---

- hosts: localhost
  tasks:
    - import_role:
        name: infrastructure

- hosts: bastion
  tasks:
    - import_role:
        name: host_prep
        tasks_from: bastion
    - import_role:
        name: openshift_install
